---
- name: allow port 22
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.

- name: allow port 3306
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3306
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.

- name: allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: icmp accept
  iptables:
    chain: INPUT
    protocol: icmp
    ctstate: NEW
    jump: ACCEPT

- name: set the policy for the INPUT chain to DROP
  iptables:
    chain: INPUT
    policy: DROP
