---
- name: installing mysql
  hosts: mysql
  user: ubuntu
  become: yes

  vars_files:
    - password.yml

  roles:
  - mysql

#ansible-playbook mysql.yml -i hosts --private-key=~/Downloads/april20.pem --ask-vault-pass
